"""Configuration for the intraday options autotrader."""

from pathlib import Path

TICKERS = [
    "SPY",
    "QQQ",
    "IWM",
    "DIA",
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "META",
    "GOOGL",
    "TSLA",
    "AMD",
    "NFLX",
    "CRM",
    "INTC",
]
CORE_TICKERS = [
    "SPY",
    "QQQ",
    "IWM",
    "DIA",
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "META",
    "GOOGL",
    "TSLA",
    "AMD",
    "NFLX",
    "CRM",
    "INTC",
    "AVGO",
    "ADBE",
    "ORCL",
    "JPM",
    "XOM",
]
BAR_TIMEFRAME = "5Min"
SIGNAL_LOOKBACK = 20
MAX_POSITIONS = 2
POSITION_SIZE_USD = 500
PROFIT_TARGET_PCT = 0.80
STOP_LOSS_PCT = 0.45
DAILY_LOSS_LIMIT_USD = 300.0
CONSECUTIVE_LOSS_LIMIT = 3
MARKET_OPEN = "09:30"
HARD_CLOSE_TIME = "15:45"
NO_NEW_TRADES_AFTER = "15:15"
PAPER = True
LOOP_INTERVAL_SECONDS = 60
SCAN_MORNING_TIME = "09:35"

MIN_SHARE_PRICE = 10
MAX_SHARE_PRICE = 800
SCREENER_TOP_N = 20
MOVER_SYMBOLS_PER_SIDE = 10
SCAN_INTRADAY_BARS = 60
SCAN_DAILY_BARS = 30
RVOL_MIN = 1.5
ATR_PCT_MIN = 1.5
VWAP_NEUTRAL_BAND_PCT = 0.1
ROC_PERIOD = 10
ROC_BULL_MIN = 0.3
ROC_BEAR_MAX = -0.3
IV_RANK_MIN = 20.0
IV_RANK_MAX = 60.0
EARNINGS_LOOKAHEAD_DAYS = 2
EARNINGS_CHECK_STRICT = False

PDT_MIN_EQUITY = 25000.0
PDT_MAX_DAY_TRADES_5D = 3
ENFORCE_PDT_GUARD = True

MIN_OPTION_OPEN_INTEREST = 500
MIN_OPTION_DAILY_VOLUME = 100
MAX_OPTION_SPREAD_PCT = 15.0
MIN_DTE_TRADING_DAYS = 2
MAX_DTE_TRADING_DAYS = 5

EASTERN_TZ = "US/Eastern"
CENTRAL_TZ = "US/Central"
RATE_LIMIT_SLEEP_SECONDS = 0.3
CLOSED_MIN_SLEEP_SECONDS = 60
CLOSED_MAX_SLEEP_SECONDS = 900
TRADES_CSV_PATH = Path(__file__).resolve().parent / "trades.csv"

ALPACA_PAPER_BASE_URL = "https://paper-api.alpaca.markets"
ALPACA_DATA_BASE_URL = "https://data.alpaca.markets"
